# Generated by Django 3.2.21 on 2023-09-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvidoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_digitada_na_ouvidoria', models.CharField(max_length=255)),
                ('data_criacao_ouvidoria', models.DateTimeField(auto_now_add=True)),
                ('tipo_de_ouvidoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.ouvidoria')),
                ('tipo_de_plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.plataforma')),
            ],
        ),
    ]
