# Generated by Django 3.2.21 on 2023-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvidoria',
            name='inativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='inativo',
            field=models.BooleanField(default=True),
        ),
    ]
