# Generated by Django 3.2.21 on 2023-10-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20230920_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tipo_de_ouvidoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvidoria_plataforma', to='API.ouvidoria'),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='tipo_de_plataforma',
        ),
        migrations.AddField(
            model_name='feedback',
            name='tipo_de_plataforma',
            field=models.ManyToManyField(related_name='feedbacks_plataforma', to='API.Plataforma'),
        ),
    ]
