# Generated by Django 3.2.21 on 2023-10-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20231018_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='nome_da_plataforma',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
