# Generated by Django 3.2.21 on 2023-10-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_feedback_nome_da_plataforma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='nome_da_plataforma',
        ),
    ]
