# Generated by Django 3.2.21 on 2023-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_feedback_nome_da_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='data_criacao_ouvidoria',
            field=models.DateField(auto_now_add=True),
        ),
    ]
