# Generated by Django 3.2.21 on 2023-11-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_feedback_data_criacao_ouvidoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tipo_de_ouvidoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_ouvidoria', to='API.ouvidoria'),
        ),
    ]
